### ISSUE TITLE
GNOME Shell search provider

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-shop#2]
So that searching for non-installed apps shows up in the shell overview. Example from GNOME Clocks https://git.gnome.org/browse/gnome-clocks/tree/src/search-provider.vala

**Comment by cassidyjames** [comment]
Example from GNOME Software https://github.com/GNOME/gnome-software/blob/master/src/gs-shell-search-provider.c

**Comment by jackpot51** [comment]
Implemented in https://github.com/system76/pop-shop/commit/67070568fe214c5117729625f964df30ace023d9

**Comment by sarahpandabeara** [comment]
closing per jeremy
